# 1. Configuração do Banco de Dados PostgreSQL (Conectando no Docker)
spring.datasource.url=jdbc:postgresql://localhost:5432/auth_api_db
spring.datasource.username=admin
spring.datasource.password=senha_secreta
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Configuração do Hibernate/JPA (Faz o Spring criar as tabelas sozinho)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 3. A chave do seu Token JWT (Ajuste para a sua chave)
api.security.token.secret=minha_senha_super_secreta_para_testes_locais_123!
spring.flyway.enabled=false