
api.security.token.secret=${JWT_SECRET}
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# FLYWAY
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=0
spring.flyway.locations=classpath:db/migration

# JPA ? deixar o Flyway controlar, não o Hibernate
spring.jpa.hibernate.ddl-auto=validate